language: java
install: skip
os: linux
dist: focal
jdk: openjdk11
script:
- "./gradlew asciidoc"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

deploy:
  provider: releases
  file:
    - manual/build/distributions/manual.zip
    - design/build/distributions/design.zip
    - web/build/distributions/web.zip
    - release-notes/build/distributions/release-notes.zip
  on:
    repo: ishgroup/onCourseDocs
  skip_cleanup: 'true'
